services:
  postgres:
    image: postgres:latest
    container_name: ams-postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ams
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      # - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username"]
      # test: ["CMD-SHELL", "pg_isready -U username -d pm"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: ams-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/ams --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
  mongodb_data: 